import { NextResponse } from 'next/server';
import { promises as fs } from 'node:fs';
import { hasValidSetupCookie } from '@/lib/setup-token';
import { getEnv } from '@/lib/env';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

// GET /api/setup/fix-docker?fmt=sh|ps1|json
//
// We can't run `docker compose up -d` from *inside* the panel container
// (we'd kill ourselves mid-restart). The next-best thing is to hand the
// user a single command they can run on the host that:
//   1. detects the docker socket GID (we already know it; we pre-fill it).
//   2. edits /opt/cachepanel/docker-compose.yml in place to add the GID
//      to the cachepanel service's group_add list (idempotent).
//   3. runs `docker compose up -d cachepanel`.
//
// fmt=sh   → bash script (Linux panel host; `curl | sudo bash`).
// fmt=ps1  → PowerShell script (Windows panel host; `iwr | iex` via PS).
// fmt=json → { ok, gid, script, oneliner, oneliner_ps1 } for the wizard UI.

const SOCKET_PATH = process.env.DOCKER_SOCKET || '/var/run/docker.sock';
const HOST_INSTALL_DIR = process.env.CP_HOST_DIR || '/opt/cachepanel';

export async function GET(req: Request) {
  // Allow setup-cookie OR ?fmt=sh|ps1 fetched from the public URL (the
  // scripts are benign and the user explicitly pipes them into sudo/PS —
  // gating behind a cookie that lives only inside a logged-in browser
  // would defeat the entire copy/paste flow).
  const url = new URL(req.url);
  const fmtParam = url.searchParams.get('fmt');
  const fmt: 'sh' | 'ps1' | 'json' = fmtParam === 'sh' ? 'sh' : fmtParam === 'ps1' ? 'ps1' : 'json';
  if (fmt === 'json' && !hasValidSetupCookie()) {
    return NextResponse.json({ ok: false, message: 'Setup session expired.' }, { status: 403 });
  }

  let gid: number | null = null;
  try {
    const stat = await fs.stat(SOCKET_PATH);
    gid = (stat as unknown as { gid: number }).gid;
  } catch {
    gid = null;
  }

  const env = getEnv();
  const publicUrl = env.NEXTAUTH_URL.replace(/\/+$/, '');
  const onPanelHostIsWindows = process.platform === 'win32';

  if (fmt === 'sh') {
    return new NextResponse(buildScript(gid, HOST_INSTALL_DIR), {
      status: 200,
      headers: {
        'Content-Type': 'text/x-shellscript; charset=utf-8',
        'Cache-Control': 'no-store',
      },
    });
  }
  if (fmt === 'ps1') {
    return new NextResponse(buildPs1Script(HOST_INSTALL_DIR), {
      status: 200,
      headers: {
        'Content-Type': 'text/x-powershell; charset=utf-8',
        'Cache-Control': 'no-store',
      },
    });
  }
  const oneliner = `curl -fsSL "${publicUrl}/api/setup/fix-docker?fmt=sh" | sudo bash`;
  const oneliner_ps1 = `iwr "${publicUrl}/api/setup/fix-docker?fmt=ps1" -UseBasicParsing | Select-Object -ExpandProperty Content | iex`;
  return NextResponse.json({
    ok: gid !== null || onPanelHostIsWindows,
    socketPath: SOCKET_PATH,
    gid,
    hostInstallDir: HOST_INSTALL_DIR,
    panelHostOs: process.platform,
    oneliner,
    oneliner_ps1,
    message: gid === null && !onPanelHostIsWindows
      ? `Couldn't stat ${SOCKET_PATH} from inside the container (is it mounted?). Mount it and try again.`
      : onPanelHostIsWindows
        ? `Panel is running on Windows. Use the PowerShell one-liner below on the panel host to repair Docker Desktop access.`
        : `The docker socket on your host is owned by GID ${gid}. Run the one-liner on the host to add it to cachepanel's group_add and restart the container.`,
  });
}

// Windows panel-host repair script: ensure Docker Desktop is installed and
// the running user is in docker-users so the named pipe is reachable.
function buildPs1Script(installDir: string): string {
  return `# CachePanel Windows panel-host docker-fix.
# Generated by /api/setup/fix-docker?fmt=ps1. Idempotent.
#
# What this does:
#   1. Installs Docker Desktop via winget if missing.
#   2. Ensures the current user is in the 'docker-users' local group so the
#      named pipe ( \\\\.\\pipe\\docker_engine ) is reachable without admin.
#   3. Restarts the CachePanel Windows Service so it picks up the new perms.

$ErrorActionPreference = 'Stop'
$installDir = if ($env:CP_HOST_DIR) { $env:CP_HOST_DIR } else { '${installDir}' }

# 1. Docker Desktop install
if (-not (Get-Command docker.exe -ErrorAction SilentlyContinue)) {
  Write-Host '-> Installing Docker Desktop via winget...'
  winget install -e --id Docker.DockerDesktop --accept-source-agreements --accept-package-agreements
} else {
  Write-Host "-> docker.exe present at $(Get-Command docker.exe | Select-Object -ExpandProperty Source)"
}

# 2. docker-users group membership
$me = "$env:USERDOMAIN\\$env:USERNAME"
$grp = 'docker-users'
$members = (Get-LocalGroupMember -Group $grp -ErrorAction SilentlyContinue).Name
if ($members -notcontains $me) {
  Write-Host "-> Adding $me to $grp..."
  Add-LocalGroupMember -Group $grp -Member $env:USERNAME -ErrorAction SilentlyContinue
} else {
  Write-Host "-> $me already in $grp"
}

# 3. Bounce the panel service so it picks up the new group + pipe perms.
$svc = Get-Service -Name 'CachePanel' -ErrorAction SilentlyContinue
if ($svc) {
  Write-Host '-> Restarting CachePanel service...'
  Restart-Service -Name 'CachePanel' -Force
}

Write-Host ''
Write-Host '[OK] Done. Reload /setup in your browser and re-run the Docker test.'
Write-Host '     If it still fails: Start-Service com.docker.service ; Restart-Service CachePanel'
`;
}

function buildScript(detectedGid: number | null, installDir: string): string {
  return `#!/usr/bin/env bash
# CachePanel docker-socket auto-fix.
#
# Generated by /api/setup/fix-docker. Idempotent — safe to re-run.
#
# What this does:
#   1. Stats /var/run/docker.sock to find the docker group GID on this host.
#   2. Adds that GID to the cachepanel service's group_add list in
#      ${installDir}/docker-compose.yml (in place, with a one-shot backup).
#   3. Re-creates the cachepanel container with the new group, so the
#      panel process gets read+write on the docker socket.

set -euo pipefail

INSTALL_DIR="\${CP_HOST_DIR:-${installDir}}"
COMPOSE="$INSTALL_DIR/docker-compose.yml"
SOCKET="/var/run/docker.sock"

if [[ "$EUID" -ne 0 ]]; then
  echo "Run with sudo: curl ... | sudo bash" >&2
  exit 1
fi

if [[ ! -f "$COMPOSE" ]]; then
  echo "No docker-compose.yml at $COMPOSE — is CachePanel installed at \${INSTALL_DIR}?" >&2
  exit 1
fi

if [[ ! -S "$SOCKET" ]]; then
  echo "Docker socket $SOCKET doesn't exist or isn't a socket on this host." >&2
  exit 1
fi

# Detect the socket's GID. We prefer the host-fresh stat over whatever the
# container saw, because the values match anyway and we want fresh data.
GID="$(stat -c '%g' "$SOCKET" 2>/dev/null || stat -f '%g' "$SOCKET")"
${detectedGid !== null ? `# Container reported GID ${detectedGid} — this should match.` : '# Container could not detect GID; relying on host stat above.'}
if [[ -z "$GID" ]]; then
  echo "Could not stat $SOCKET to find its GID." >&2
  exit 1
fi
echo "→ Detected docker socket GID: $GID"

# Already configured? Idempotent fast-path.
if grep -qE "^[[:space:]]+- (\\"|')?$GID(\\"|')?[[:space:]]*$" "$COMPOSE"; then
  echo "→ GID $GID is already in $COMPOSE — nothing to add."
else
  # Make a timestamped backup before we touch the file.
  BACKUP="$COMPOSE.bak.$(date +%Y%m%d%H%M%S)"
  cp "$COMPOSE" "$BACKUP"
  echo "→ Backed up compose file to $BACKUP"

  if grep -qE "^[[:space:]]+group_add:[[:space:]]*$" "$COMPOSE"; then
    # group_add: exists — append our GID as a new list item underneath it,
    # matching the surrounding indentation.
    awk -v gid="$GID" '
      BEGIN { added = 0 }
      /^[[:space:]]+group_add:[[:space:]]*$/ {
        print
        match($0, /^[[:space:]]+/)
        indent = substr($0, RSTART, RLENGTH)
        print indent "  - \\"" gid "\\""
        added = 1
        next
      }
      { print }
    ' "$COMPOSE" > "$COMPOSE.tmp" && mv "$COMPOSE.tmp" "$COMPOSE"
    echo "→ Added GID $GID to existing group_add list"
  else
    # No group_add: at all — insert a fresh block right after the
    # cachepanel service header. We look for the first line that starts
    # with "  cachepanel:" and inject after its container_name (or first
    # other property) so we don't accidentally land it inside another service.
    python3 - "$COMPOSE" "$GID" <<'PYEOF'
import sys, re
path, gid = sys.argv[1], sys.argv[2]
with open(path) as f:
    lines = f.readlines()
# Find the cachepanel: service line.
for i, line in enumerate(lines):
    if re.match(r'^  cachepanel:\\s*$', line):
        # Find the indentation level of properties (typically 4 spaces).
        # Insert group_add: after the service header, before the first child key.
        # We expect the next non-empty line to be a key like image: or container_name:.
        for j in range(i + 1, len(lines)):
            if lines[j].strip() and not lines[j].startswith('    '):
                break
            if lines[j].strip() and lines[j].startswith('    '):
                insert_at = j
                break
        else:
            insert_at = i + 1
        lines.insert(insert_at, f'    group_add:\\n')
        lines.insert(insert_at + 1, f'      - "{gid}"\\n')
        break
else:
    sys.exit("Could not find cachepanel: service in compose file")
with open(path, 'w') as f:
    f.writelines(lines)
PYEOF
    echo "→ Inserted new group_add block with GID $GID"
  fi
fi

echo "→ Ensuring docker socket bind mount exists in compose…"
if ! grep -qE "/var/run/docker\\.sock[[:space:]]*:[[:space:]]*/var/run/docker\\.sock" "$COMPOSE"; then
  python3 - "$COMPOSE" <<'PYEOF2'
import sys, re
path = sys.argv[1]
with open(path) as f:
    lines = f.readlines()
in_service = False
service_start = -1
for i, line in enumerate(lines):
    if re.match(r'^  cachepanel:\\s*$', line):
        in_service = True
        service_start = i
        continue
    if in_service and re.match(r'^  [A-Za-z]', line):
        break
    if in_service and re.match(r'^    volumes:\\s*$', line):
        lines.insert(i + 1, '      - /var/run/docker.sock:/var/run/docker.sock\\n')
        with open(path, 'w') as f:
            f.writelines(lines)
        sys.exit(0)
if service_start >= 0:
    for j in range(service_start + 1, len(lines)):
        if lines[j].strip() and lines[j].startswith('    '):
            insert_at = j
            break
    else:
        insert_at = service_start + 1
    lines.insert(insert_at, '    volumes:\\n')
    lines.insert(insert_at + 1, '      - /var/run/docker.sock:/var/run/docker.sock\\n')
    with open(path, 'w') as f:
        f.writelines(lines)
PYEOF2
  echo "→ Added /var/run/docker.sock bind mount"
fi

echo "→ Recreating cachepanel container so the new group/mount takes effect…"
cd "$INSTALL_DIR"
docker compose up -d cachepanel

echo
echo "✅ Done. Reload /setup in your browser and re-run the Docker test."
echo "   If it still fails, check 'docker compose logs cachepanel'."
`;
}
